//! OpenAPI endpoint Markdown format-aware tokenizer.
//!
//! Extracts structured tokens from Markdown generated by `format_endpoint()`
//! in `openapi_parser.rs`. Structured parts (HTTP method, path segments,
//! parameter names, status codes, content types, schema fields) are extracted
//! via fixed pattern matching. Natural language parts (summary, description)
//! go through jieba tokenization. All tokens are merged, deduped, and joined
//! with spaces.

use super::vector_store::tokenize_for_fts;

/// Tokenize an OpenAPI endpoint Markdown content with format-aware extraction.
///
/// Extracts structured tokens:
/// - HTTP method (POST, GET, etc.)
/// - Path segments (stripping `{}`, e.g. api, documents, documentId, publish)
/// - Parameter names (from Parameters table Name column)
/// - Status codes (from Responses table Status column)
/// - Content-Type values (from `- Content-Type: value` lines)
/// - Schema field names (from `Schema: { field: type, ... }` lines)
///
/// Natural language parts (summary, description) are tokenized with jieba.
/// All tokens merged, deduped, and joined with spaces.
pub fn tokenize_openapi_endpoint(markdown: &str) -> String {
    let mut tokens = Vec::new();

    extract_method_and_path(markdown, &mut tokens);
    extract_parameter_names(markdown, &mut tokens);
    extract_status_codes(markdown, &mut tokens);
    extract_content_types(markdown, &mut tokens);
    extract_schema_fields(markdown, &mut tokens);

    // Natural language text through jieba
    let natural_text = extract_natural_text(markdown);
    let jieba_tokens = tokenize_for_fts(&natural_text);
    tokens.extend(jieba_tokens.split_whitespace().map(String::from));

    tokens.sort();
    tokens.dedup();
    tokens.join(" ")
}

/// Parse `## METHOD /path` heading to extract HTTP method and path segments.
/// Path segments have `{}` stripped (e.g. `{documentId}` becomes `documentId`).
fn extract_method_and_path(markdown: &str, tokens: &mut Vec<String>) {
    for line in markdown.lines() {
        let trimmed = line.trim();
        // Match: ## POST /api/documents/{documentId}/publish
        if let Some(rest) = trimmed.strip_prefix("## ") {
            let mut parts = rest.splitn(2, ' ');
            if let Some(method) = parts.next() {
                tokens.push(method.to_uppercase());
            }
            if let Some(path) = parts.next() {
                for segment in path.split('/') {
                    let seg = segment.trim();
                    if seg.is_empty() {
                        continue;
                    }
                    // Strip {} wrappers: {documentId} -> documentId
                    let cleaned = seg
                        .strip_prefix('{')
                        .and_then(|s| s.strip_suffix('}'))
                        .unwrap_or(seg);
                    if !cleaned.is_empty() {
                        tokens.push(cleaned.to_string());
                    }
                }
            }
            break; // Only first ## heading
        }
    }
}

/// Parse Parameters table rows: `| Name | In | Type | Required | Description |`
/// Extracts the Name column value from data rows (after the header + separator).
fn extract_parameter_names(markdown: &str, tokens: &mut Vec<String>) {
    let mut in_params_table = false;
    let mut header_skipped = false;

    for line in markdown.lines() {
        let trimmed = line.trim();

        if trimmed == "### Parameters" {
            in_params_table = true;
            header_skipped = false;
            continue;
        }

        if in_params_table {
            if trimmed.starts_with('|') && trimmed.ends_with('|') {
                // Skip table header and separator rows
                if !header_skipped {
                    // First | line is the header, next is separator
                    if trimmed.contains("---") {
                        header_skipped = true;
                    }
                    continue;
                }
                // Data row: | Name | In | Type | Required | Description |
                let cols: Vec<&str> = trimmed.split('|').collect();
                // cols: ["", " Name ", " In ", " Type ", " Required ", " Description ", ""]
                if cols.len() >= 2 {
                    let name = cols[1].trim();
                    if !name.is_empty() {
                        tokens.push(name.to_string());
                    }
                }
            } else if !trimmed.is_empty() && !trimmed.starts_with('|') {
                // End of table
                in_params_table = false;
            }
        }
    }
}

/// Parse Responses table rows: `| Status | Description |`
/// Extracts the Status column value from data rows.
fn extract_status_codes(markdown: &str, tokens: &mut Vec<String>) {
    let mut in_responses_table = false;
    let mut header_skipped = false;

    for line in markdown.lines() {
        let trimmed = line.trim();

        if trimmed == "### Responses" {
            in_responses_table = true;
            header_skipped = false;
            continue;
        }

        if in_responses_table {
            if trimmed.starts_with('|') && trimmed.ends_with('|') {
                if !header_skipped {
                    if trimmed.contains("---") {
                        header_skipped = true;
                    }
                    continue;
                }
                let cols: Vec<&str> = trimmed.split('|').collect();
                if cols.len() >= 2 {
                    let status = cols[1].trim();
                    if !status.is_empty() {
                        tokens.push(status.to_string());
                    }
                }
            } else if !trimmed.is_empty() && !trimmed.starts_with('|') {
                in_responses_table = false;
            }
        }
    }
}

/// Parse `- Content-Type: value` lines in Request Body section.
fn extract_content_types(markdown: &str, tokens: &mut Vec<String>) {
    for line in markdown.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("- Content-Type: ") {
            let ct = rest.trim();
            if !ct.is_empty() {
                tokens.push(ct.to_string());
            }
        }
    }
}

/// Parse `Schema: { field: type, ... }` lines to extract field names.
fn extract_schema_fields(markdown: &str, tokens: &mut Vec<String>) {
    for line in markdown.lines() {
        let trimmed = line.trim();
        // Match lines like:   Schema: { field1: type, field2: type (required) }
        if let Some(schema_start) = trimmed.find("Schema: {") {
            let brace_content = &trimmed[schema_start + 9..];
            // Extract content between { and }
            if let Some(inner) = brace_content
                .strip_prefix(' ')
                .and_then(|s| s.strip_suffix('}'))
                .or_else(|| brace_content.strip_suffix(" }"))
            {
                for field_def in inner.split(',') {
                    let field_def = field_def.trim();
                    // field_def looks like "fieldName: type" or "fieldName: type (required)"
                    if let Some(name) = field_def.split(':').next() {
                        let name = name.trim();
                        if !name.is_empty() {
                            tokens.push(name.to_string());
                        }
                    }
                }
            }
        }
    }
}

/// Extract natural language text between the heading and first `###` section.
/// This captures summary and description paragraphs.
fn extract_natural_text(markdown: &str) -> String {
    let mut text_parts = Vec::new();
    let mut past_heading = false;

    for line in markdown.lines() {
        let trimmed = line.trim();

        // Detect the ## heading line
        if trimmed.starts_with("## ") && !past_heading {
            past_heading = true;
            continue;
        }

        // Stop at first ### section
        if trimmed.starts_with("### ") {
            break;
        }

        if past_heading && !trimmed.is_empty() {
            text_parts.push(trimmed.to_string());
        }
    }

    text_parts.join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extract_method_and_path_from_heading() {
        let md = "## POST /api/documents/{documentId}/publish\n\nSome description.";
        let mut tokens = Vec::new();
        extract_method_and_path(md, &mut tokens);
        assert_eq!(
            tokens,
            vec!["POST", "api", "documents", "documentId", "publish"]
        );
    }

    #[test]
    fn extract_parameter_names_from_table() {
        let md = "\
### Parameters

| Name | In | Type | Required | Description |
|------|------|------|----------|-------------|
| documentId | path | string | Yes | Document ID |
| userId | query | string | No | User filter |";
        let mut tokens = Vec::new();
        extract_parameter_names(md, &mut tokens);
        assert!(tokens.contains(&"documentId".to_string()));
        assert!(tokens.contains(&"userId".to_string()));
        assert_eq!(tokens.len(), 2);
    }

    #[test]
    fn extract_status_codes_from_table() {
        let md = "\
### Responses

| Status | Description |
|--------|-------------|
| 200 | Success |
| 404 | Not found |";
        let mut tokens = Vec::new();
        extract_status_codes(md, &mut tokens);
        assert!(tokens.contains(&"200".to_string()));
        assert!(tokens.contains(&"404".to_string()));
        assert_eq!(tokens.len(), 2);
    }

    #[test]
    fn extract_content_type_values() {
        let md = "### Request Body\n\nSome body.\n- Content-Type: application/json\n- Content-Type: text/plain";
        let mut tokens = Vec::new();
        extract_content_types(md, &mut tokens);
        assert!(tokens.contains(&"application/json".to_string()));
        assert!(tokens.contains(&"text/plain".to_string()));
    }

    #[test]
    fn extract_schema_field_names() {
        let md = "  Schema: { name: string, age: integer (required) }";
        let mut tokens = Vec::new();
        extract_schema_fields(md, &mut tokens);
        assert!(tokens.contains(&"name".to_string()));
        assert!(tokens.contains(&"age".to_string()));
        assert_eq!(tokens.len(), 2);
    }

    #[test]
    fn extract_natural_text_between_heading_and_section() {
        let md = "\
## POST /api/test

This is the summary.

This is a longer description of the endpoint.

### Parameters

| Name | In |";
        let text = extract_natural_text(md);
        assert!(text.contains("This is the summary."));
        assert!(text.contains("This is a longer description"));
        assert!(!text.contains("Parameters"));
    }

    #[test]
    fn full_tokenize_produces_deduped_tokens() {
        let md = "\
## POST /api/documents/{documentId}/publish

Publish a document. Publish endpoint.

### Parameters

| Name | In | Type | Required | Description |
|------|------|------|----------|-------------|
| documentId | path | string | Yes | Document ID |

### Responses

| Status | Description |
|--------|-------------|
| 200 | Success |";

        let result = tokenize_openapi_endpoint(md);
        let tokens: Vec<&str> = result.split_whitespace().collect();
        // Check structured tokens are present
        assert!(tokens.contains(&"POST"));
        assert!(tokens.contains(&"api"));
        assert!(tokens.contains(&"documents"));
        assert!(tokens.contains(&"documentId"));
        assert!(tokens.contains(&"publish"));
        assert!(tokens.contains(&"200"));
        // Check no duplicate tokens
        let mut sorted = tokens.clone();
        sorted.sort();
        sorted.dedup();
        assert_eq!(tokens.len(), sorted.len(), "tokens should be deduped");
    }

    // --- End-to-end tests for tokenize_openapi_endpoint() public API ---

    // User Story: US-CORE-027
    // Covers: tokenize_openapi_endpoint extracts the HTTP method from the ## heading
    //         as a token in the final output string.
    #[test]
    fn tokenize_extracts_method_from_heading() {
        let md = "## POST /api/documents/{documentId}/publish\n\nPublish a document.";
        let result = tokenize_openapi_endpoint(md);
        let tokens: Vec<&str> = result.split_whitespace().collect();
        assert!(
            tokens.contains(&"POST"),
            "output should contain 'POST' as a token, got: {:?}",
            tokens
        );
    }

    // User Story: US-CORE-027
    // Covers: tokenize_openapi_endpoint extracts path segments from the heading,
    //         stripping curly braces from path parameters (e.g. {documentId} -> documentId).
    #[test]
    fn tokenize_extracts_path_segments() {
        let md = "## POST /api/documents/{documentId}/publish\n\nPublish a document.";
        let result = tokenize_openapi_endpoint(md);
        let tokens: Vec<&str> = result.split_whitespace().collect();
        assert!(
            tokens.contains(&"api"),
            "output should contain 'api' token, got: {:?}",
            tokens
        );
        assert!(
            tokens.contains(&"documents"),
            "output should contain 'documents' token, got: {:?}",
            tokens
        );
        assert!(
            tokens.contains(&"documentId"),
            "output should contain 'documentId' with braces stripped, got: {:?}",
            tokens
        );
        assert!(
            tokens.contains(&"publish"),
            "output should contain 'publish' token, got: {:?}",
            tokens
        );
        // Verify curly braces are not present
        assert!(
            !result.contains('{') && !result.contains('}'),
            "output should not contain curly braces, got: {}",
            result
        );
    }

    // User Story: US-CORE-027
    // Covers: tokenize_openapi_endpoint extracts parameter names from the Parameters table.
    #[test]
    fn tokenize_extracts_parameter_names() {
        let md = "\
## GET /api/users

List users.

### Parameters

| Name | In | Type | Required | Description |
|------|------|------|----------|-------------|
| documentId | path | string | Yes | Document ID |";
        let result = tokenize_openapi_endpoint(md);
        let tokens: Vec<&str> = result.split_whitespace().collect();
        assert!(
            tokens.contains(&"documentId"),
            "output should contain 'documentId' from parameters table, got: {:?}",
            tokens
        );
    }

    // User Story: US-CORE-027
    // Covers: tokenize_openapi_endpoint extracts status codes from the Responses table.
    #[test]
    fn tokenize_extracts_status_codes() {
        let md = "\
## GET /api/users

List users.

### Responses

| Status | Description |
|--------|-------------|
| 200 | OK |
| 404 | Not Found |";
        let result = tokenize_openapi_endpoint(md);
        let tokens: Vec<&str> = result.split_whitespace().collect();
        assert!(
            tokens.contains(&"200"),
            "output should contain status code '200', got: {:?}",
            tokens
        );
        assert!(
            tokens.contains(&"404"),
            "output should contain status code '404', got: {:?}",
            tokens
        );
    }

    // User Story: US-CORE-027
    // Covers: tokenize_openapi_endpoint extracts Content-Type values from Request Body.
    #[test]
    fn tokenize_extracts_content_types() {
        let md = "\
## POST /api/users

Create a user.

### Request Body

User data.
- Content-Type: application/json";
        let result = tokenize_openapi_endpoint(md);
        let tokens: Vec<&str> = result.split_whitespace().collect();
        assert!(
            tokens.contains(&"application/json"),
            "output should contain 'application/json' content type, got: {:?}",
            tokens
        );
    }

    // User Story: US-CORE-027
    // Covers: tokenize_openapi_endpoint extracts schema field names from Schema: lines.
    #[test]
    fn tokenize_extracts_schema_fields() {
        let md = "\
## POST /api/users

Create a user.

### Request Body

User data.
- Content-Type: application/json
  Schema: { id: integer (required), name: string }";
        let result = tokenize_openapi_endpoint(md);
        let tokens: Vec<&str> = result.split_whitespace().collect();
        assert!(
            tokens.contains(&"id"),
            "output should contain schema field 'id', got: {:?}",
            tokens
        );
        assert!(
            tokens.contains(&"name"),
            "output should contain schema field 'name', got: {:?}",
            tokens
        );
    }

    // User Story: US-CORE-027
    // Covers: tokenize_openapi_endpoint merges natural language text through jieba
    //         segmentation. Chinese summary/description text must produce Chinese tokens.
    #[test]
    fn tokenize_merges_natural_language_with_jieba() {
        let md = "\
## POST /api/documents/publish

发布文档到线上环境

### Parameters

| Name | In | Type | Required | Description |
|------|------|------|----------|-------------|
| docId | path | string | Yes | Document ID |";
        let result = tokenize_openapi_endpoint(md);
        // The Chinese text "发布文档到线上环境" should produce Chinese tokens via jieba.
        // We verify that at least one Chinese character appears in the output,
        // confirming jieba segmentation was applied to the natural language text.
        let has_chinese = result
            .chars()
            .any(|c| ('\u{4e00}'..='\u{9fff}').contains(&c));
        assert!(
            has_chinese,
            "output should contain Chinese characters from jieba tokenization of natural language, got: {}",
            result
        );
    }

    // User Story: US-CORE-027
    // Covers: tokenize_openapi_endpoint deduplicates tokens so that a token appearing
    //         in both the heading and the parameters table appears only once.
    #[test]
    fn tokenize_deduplicates_tokens() {
        let md = "\
## POST /api/documents/{documentId}/publish

Publish a document.

### Parameters

| Name | In | Type | Required | Description |
|------|------|------|----------|-------------|
| documentId | path | string | Yes | Document ID |";
        let result = tokenize_openapi_endpoint(md);
        let tokens: Vec<&str> = result.split_whitespace().collect();
        let document_id_count = tokens.iter().filter(|&t| t == &"documentId").count();
        assert_eq!(
            document_id_count, 1,
            "'documentId' should appear exactly once (deduped), but appeared {} times in: {:?}",
            document_id_count, tokens
        );
    }

    // User Story: US-CORE-027
    // Covers: tokenize_openapi_endpoint handles a minimal endpoint with no parameters,
    //         no request body, and no responses. Must still produce method and path tokens.
    #[test]
    fn tokenize_handles_minimal_endpoint() {
        let md = "## GET /health";
        let result = tokenize_openapi_endpoint(md);
        let tokens: Vec<&str> = result.split_whitespace().collect();
        assert!(
            tokens.contains(&"GET"),
            "minimal endpoint should contain 'GET', got: {:?}",
            tokens
        );
        assert!(
            tokens.contains(&"health"),
            "minimal endpoint should contain 'health', got: {:?}",
            tokens
        );
        assert!(
            !tokens.is_empty(),
            "output should be non-empty for minimal endpoint"
        );
    }
}
